services:
  app:
    build: .
    container_name: administrative_backend
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=my_password
      - DB_NAME=my_database
      - DB_PORT=3306
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8
    restart: always
    container_name: my_database
    environment:
      MYSQL_ROOT_PASSWORD: my_password
      MYSQL_DATABASE: my_database
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
